config/routes.rb
LoginTemplate::Application.routes.draw do
  
  resources :users
  match '/help',    to: 'pages#help',    via: 'get'
  match '/home',    to: 'pages#home',    via: 'get'
  match '/about',   to: 'pages#about',   via: 'get'
  match '/contact', to: 'pages#contact', via: 'get'
  match '/signup',  to: 'users#new',     via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  resources :sessions, only: [:create, :destroy]

  root 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
	before_save { self.email = email.downcase }	

	validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }

  def self.new_guest
    new { |u| u.guest = true }
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])  
      session[:remember_token] = user.id    
      sign_in user
      redirect_back_or user
    else
      flash[:error] = 'Invalid email/password combination' 
      redirect_to root_path
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:index, :destroy]

  def new
  	@user = User.new
  end

  def show
    begin
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "User don't found"
      redirect_to root_url
    end
  end

  def index
    @users = User.paginate(:page => params[:page], :per_page => 20)
  end

  def create
    @user = User.new(user_params)   
    if @user.save
      session[:remember_token] = @user.id
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    begin
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "User don't found"
      redirect_to root_url
    end
  end

  def update
    begin
      @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        flash[:success] = "Profile updated"
        redirect_to @user
      else
        render 'edit'
      end
    rescue ActiveRecord::RecordNotFound
      flash.now[:error] = "User don't found"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :avatar, :password,
                                   :password_confirmation)
    end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to root_url, notice: "Please sign in."
      end
    end

    def correct_user      
      begin       
        @user = User.find(params[:id])
        unless current_user?(@user)
          flash[:warning] = "You don't have access to this route"
          redirect_to(root_url) 
        end
      rescue ActiveRecord::RecordNotFound
        flash.now[:error] = "User don't found"
      end
    end

    def admin_user
      unless current_user.admin?
        flash[:warning] = "You don't have access to this route"
        redirect_to(root_url) 
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
    base_title = "Loggin template"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    remember_token = User.new_remember_token
    cookies[:remember_token] = remember_token
    #user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = User.find(session[:remember_token])
  end

  def signed_in?
    !current_user == nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = cookies[:remember_token]
    session[:remember_token] ? @current_user = User.find(session[:remember_token]) : @current_user = nil
    #@current_user = User.find(1)
  end

  def sign_out    
    cookies.delete(:remember_token)
    self.current_user = nil
    session[:remember_token] = nil
    current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/forms/_edit_user.html.erb
<%= form_for @user, :html => {:multipart => true} do |f| %>
    	<%= render 'shared/error_messages' %>
      <div class="small-offset-2  medium-offset-2 small-8 medium-8  columns" >
        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :avatar %>
        <%= f.file_field :avatar %>
      
        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Save changes", class: "button small right" %>
      </div>
      
    <% end %>

app/views/forms/_login.html.erb
<%= form_for(:session, url: sessions_path) do |f| %>
  <li class="has-form">
    <div class="row ">
      <div class="large-6 small-6 columns">
        <%= f.text_field :email, :placeholder => "Mail" %>
      </div>
      <div class="large-6 small-6 columns">
        <%= f.password_field :password, :placeholder => "Password" %>
      </div>
    </div>
  </li>
  
  <li class="has-form">
    <%= f.submit "Sign in", class: "button success" %>
  </li>
<% end %>

app/views/forms/_register.html.erb
<%= form_for @user, :html => {:multipart => true} do |f| %>
    	<%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :avatar %>
      <%= f.file_field :avatar %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "button right" %>
    <% end %>

app/views/layouts/_footer.html.erb
<div class="zurb-footer-bottom">
  <div class="row">
    <div class="large-4 medium-4 small-4 push-8 columns">
      <ul class="home-social">
          <li><a href="http://www.twitter.com/ZURB" class="twitter"></a></li>
          <li><a href="http://www.facebook.com/ZURB" class="facebook"></a></li>
          <li><a href="http://zurb.com/contact" class="mail"></a></li>
        </ul>
     </div>
     <div class="large-8 medium-8 small-8 pull-4 columns">
        <a href="http://www.usach.cl" class="zurb-logo regular"><%= image_tag "udesantiago_logo.png"  %></a>
        <ul class="zurb-links">
          <li><%= link_to "Home",   root_path %></li>
          <li><%= link_to "About",   about_path %></li>
          <li><%= link_to "Contact",   contact_path %></li>
          <li><%= link_to "Help",   help_path %></li>
        </ul>
       <p class="copyright">&copy; 1998&dash;2014 ZURB, Inc. All rights reserved.</p>
    </div>          
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "My Site", root_path%></a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <% if signed_in? %>           
        <li class="avatar">
          <a href=<%= user_path(current_user) %>>
            <% if current_user.avatar.present? %>
              <%= image_tag current_user.avatar_url  %>
            <% else %>
              <%= image_tag "icon-user-default.png"  %>
            <% end %>
            <%= current_user.name %> 
          </a>
        </li>
                
        <li class="divider"></li>
        <li class="has-form">
          <%= link_to "Sign out", signout_path, method: "delete", class: "button success" %>
        </li>  
        
      <% else %>

        <%= render "forms/login" %>
      <% end %>
    </ul>    
  </section>
</nav>

app/views/layouts/_shim.html.erb
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= render "layouts/shim" %>
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= full_title(yield(:title)) %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="row error-container">
      <div class="small-10 small-offset-1 columns">
        <% flash.each do |key, value| %>
          <div class="alert-box <%= key %> radius">
            <%= value %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>
      </div>
    </div>

      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
      <%= render "layouts/footer" %>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/about.html.erb
<% provide(:title, 'About Us') %>

<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<div class="row">
	<h1 style="text-align: center;">My site</h1>
  <hr>
  <div class="row" data-equalizer>
	  <div class="large-6 columns " data-equalizer-watch>
	    <p class="text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce porttitor ligula ac mi consectetur, ac scelerisque est congue. Morbi in sem at urna tempus adipiscing. Nam eleifend risus vitae rutrum eleifend. Integer pellentesque, ligula ut consectetur lobortis, libero quam ultrices sapien, eu eleifend quam massa sed tortor. Aliquam tempor fringilla ultricies. Nulla eleifend venenatis sem nec blandit. Aliquam at venenatis tortor. Aliquam eu risus in felis ultricies posuere dapibus ut urna.</p>
	  </div>
	  <div class="large-6 columns " data-equalizer-watch>
	    <p class="text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce porttitor ligula ac mi consectetur, ac scelerisque est congue. Morbi in sem at urna tempus adipiscing. Nam eleifend risus vitae rutrum eleifend. Integer pellentesque, ligula ut consectetur lobortis, libero quam ultrices sapien, eu eleifend quam massa sed tortor. Aliquam tempor fringilla ultricies. Nulla eleifend venenatis sem nec blandit. Aliquam at venenatis tortor. Aliquam eu risus in felis ultricies posuere dapibus ut urna.</p>
	  </div>
	</div>
  <div class="panel">
  	<div class="row">
  		<div class="small-8 small-offset-2 columns">
  		<br>
  		<p class="text-center">Bienvenido! si eres nuevo por acá, entonces por favor <%= link_to "registrate", signup_path %> para utilizar la aplicación. Si solo estas de paso, puedes echar un vistazo (por <%= link_to "acá", "#" %>), pero no podras votar, ni postular igualitos. Y obviamente si ya eres parte del sitio loggeate arriba para continuar!</p>
  		</div>
  	</div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="error-container">
    <div data-alert class="alert-box error round">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_sidebar.html.erb
<div class="sidebar">
			<div class="header-block">				
				<a class="th radius" href="#">
					<% if @user.avatar.present? %>
						<%= image_tag @user.avatar_url  %>
					<% else %>
						<%= image_tag "icon-user-default.png"  %>
					<% end %>
				</a>
				<div class="user-info">
					<h1><%= @user.name %></h1>
					<h5><%= @user.email %></h5>
				</div>
			</div>
			<nav>
				<ul class="side-nav">
					<li class="divider"></li>
					<li>
						<%= link_to "Settings", edit_user_path(current_user) %>
					</li>
					<li>
						<% if current_user.admin? %>
							<%= link_to "Users", users_url %><span class="label"><%= User.all.length %></span>
						<% else %>
							<a href="#">Menu 2<span class="label">1</span></a>
						<% end %>
					</li>
					<li>
						<a href="#">Menu 1</a>
					</li>
				</ul>
			</nav>
		</div>

app/views/users/edit.html.erb
<% provide(:title, @user.name) %>

<div class="row large">
	<div class="small-4 medium-3 columns">
		<%= render "shared/user_sidebar" %>
	</div>
	<div class="small-8 medium-9 columns">
		<br><br>
		<div class="row">					  
		    <%= render "forms/edit_user" %>		  
		</div>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<div class="row">
	<div class="small-12 medium-12 columns">
		<h1>All users</h1>
		<div class="pagination-centered">
			<%= foundation_paginate @users%>
		</div>
		<ul class="users">
			<hr>
		  <% @users.each do |user| %>
		    <li>
		    	<a class="th" href="#">
			      <% if user.avatar.present? %>
							<%= image_tag user.avatar_url  %>
						<% else %>
							<%= image_tag "icon-user-default.png"  %>
						<% end %>
					</a>
		      <%= link_to user.name, user, class: "user-link"%>
		      <% if current_user.admin? && !current_user?(user) %>				    
				    <div class="button-bar right">
						  <ul class="button-group round">
						    <li><%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" }, class: "small button secondary" %></li>
						    <li><a href="#" class="small button secondary">Button 2</a></li>
						    <li><a href="#" class="small button secondary">Button 3</a></li>
						  </ul>					  
						</div>
				  <% end %>
		    </li>
		    <hr>
		  <% end %>
		</ul>
		<div class="pagination-centered">
			<%= foundation_paginate @users%>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
	<h1>Sign up</h1>
  <div class="small-6 small-offset-3 columns">
    <%= render "forms/register" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row large">
	<div class="small-4 medium-3 columns">
		<%= render "shared/user_sidebar" %>
	</div>
	<div class="small-8 medium-9 columns" style="margin-top: 30px;">
		<ul class="no-bullet">
			<li><strong>Nombre:</strong> <%= @user.name %></li>
			<li><strong>Mail:</strong> <%= @user.email %></li>
			<li><strong>Se unio en:</strong> <%= @user.created_at %></li>
		</ul>
	</div>
</div>